---
# code: language=ansible
- name: Create/update setting file
  ansible.builtin.template:
    src: setting.j2
    dest: /etc/logrotate.d/{{ item.name }}
    mode: "0644"
  loop: "{{ logrotate_settings }}"
