---
# code: language=ansible
- name: Import package task
  ansible.builtin.import_tasks:
    file: package.yml
  tags:
    - role_logrotate_package
- name: Import setting task
  ansible.builtin.import_tasks:
    file: setting.yml
  tags:
    - role_logrotate_setting
