---
# code: language=ansible
- name: Include package task
  ansible.builtin.import_tasks:
    file: package.yml
  tags: package
- name: Include setting task
  ansible.builtin.import_tasks:
    file: setting.yml
  tags: setting
