---
logrotate_settings:
  nginx:
    paths:
      - /var/log/nginx/*.log
    frequency: daily
    missingok: true
    ## rotate: 14 => 35
    rotate: 35
    compress: true
    delaycompress: true
    notifempty: true
    create:
      mode: "0640"
      user: www-data
      group: adm
    sharedscripts: true
    prerotate: |
      if [ -d /etc/logrotate.d/httpd-prerotate ]; then \
        run-parts /etc/logrotate.d/httpd-prerotate; \
      fi \
    postrotate: invoke-rc.d nginx rotate >/dev/null 2>&1
  apache2:
    paths:
      - /var/log/apache2/*.log
    frequency: daily
    missingok: true
    ## 14 => 32に引き上げ
    rotate: 14
    compress: true
    delaycompress: true
    notifempty: true
    create:
      mode: "0640"
      user: root
      group: adm
    sharedscripts: true
    prerotate: |
      if [ -d /etc/logrotate.d/httpd-prerotate ]; then
          run-parts /etc/logrotate.d/httpd-prerotate
      fi
    postrotate: |
      if pgrep -f ^/usr/sbin/apache2 > /dev/null; then
          invoke-rc.d apache2 reload 2>&1 | logger -t apache2.logrotate
      fi
  mariadb:
    paths:
      - /var/lib/mysql/mysqld.log
      - /var/log/mysql/mysql.log
      - /var/lib/mysql/mariadb.log
      - /var/log/mysql/mysql-slow.log
      - /var/log/mysql/mariadb-slow.log
      - /var/log/mysql/error.log
    frequency: monthly
    compress: true
    delaycompress: true
    missingok: true
    notifempty: true
    rotate: 6
    maxsize: 500M
    sharedscripts: true
    postrotate: |
      if test -r /etc/mysql/debian.cnf
      then
        EXTRAPARAM='--defaults-file=/etc/mysql/debian.cnf'
      fi
      if test -x /usr/bin/mariadb-admin
      then
        /usr/bin/mariadb-admin $EXTRAPARAM --local flush-error-log \
          flush-engine-log flush-general-log flush-slow-log
      fi
  redmine:
    paths:
      - /opt/redmine/log/*.log
    frequency: daily
    missingok: true
    rotate: 14
    compress: true
    delaycompress: true
    notifempty: true
    copytruncate: true
  max_params:
    paths:
      - /var/log/syslog
      - /var/log/mail.info
      - /var/log/mail.warn
      - /var/log/mail.err
      - /var/log/mail.log
      - /var/log/daemon.log
      - /var/log/kern.log
      - /var/log/auth.log
      - /var/log/user.log
      - /var/log/lpr.log
      - /var/log/cron.log
      - /var/log/debug
      - /var/log/cron.log
      - /var/log/messages
    ## optional
    frequency: daily
    compress: true
    delaycompress: true
    rotate: 14
    minsize: 500M
    missingok: true
    nomissingok: true
    notifempty: true
    copy: true
    copytruncate: true
    create:
      mode: "0640"
      user: www-data
      group: adm
    su:
      user: root
      group: root
    sharedscripts: true
    dateext: true
    dateformat: -%Y%m%d
    prerotate: |
      if [ -d /etc/logrotate.d/httpd-prerotate ]; then \
        run-parts /etc/logrotate.d/httpd-prerotate; \
      fi \
    postrotate: invoke-rc.d nginx rotate >/dev/null 2>&1
