---
logrotate_entries:
  - name: nginx
    paths:
      - /var/log/nginx/*.log
    frequency: daily
    missingok: true
    rotate: 14
    compress: true
    delaycompress: true
    notifempty: true
    create: true
    create_mode: "0640"
    create_user: www-data
    create_group: adm
    sharedscripts: true
    prerotate: |
      if [ -d /etc/logrotate.d/httpd-prerotate ]; then \
        run-parts /etc/logrotate.d/httpd-prerotate; \
      fi \
    postrotate: invoke-rc.d nginx rotate >/dev/null 2>&1
  - name: mariadb
    paths:
      - /var/lib/mysql/mysqld.log
      - /var/log/mysql/mysql.log
      - /var/lib/mysql/mariadb.log
      - /var/log/mysql/mysql-slow.log
      - /var/log/mysql/mariadb-slow.log
      - /var/log/mysql/error.log
    frequency: monthly
    compress: true
    delaycompress: true
    rotate: 6
    maxsize: 500M
    sharedscripts: true
    postrotate: |
      if test -r /etc/mysql/debian.cnf
      then
        EXTRAPARAM='--defaults-file=/etc/mysql/debian.cnf'
      fi
      if test -x /usr/bin/mariadb-admin
      then
        /usr/bin/mariadb-admin $EXTRAPARAM --local flush-error-log \
          flush-engine-log flush-general-log flush-slow-log
      fi
