---
# code: language=ansible
- name: Verify
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Example assertion
      ansible.builtin.assert:
        that: true
    ## パッケージのテスト
    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto
    - name: Assert package
      ansible.builtin.assert:
        that:
          - ansible_facts.packages['logrotate'] is defined
    ## サービスのテスト
    - name: Populate service facts
      ansible.builtin.service_facts:
    - name: Assert service
      ansible.builtin.assert:
        that:
          - ansible_facts.services['logrotate.service'] is defined
    # 設定ファイルのテスト
    - name: Check logrotate entry(Nginx)
      ansible.builtin.stat:
        path: /etc/logrotate.d/nginx
      register: result
    - name: Assert file(Nginx logrotate setting)
      ansible.builtin.assert:
        that:
          - result.stat.exists
    - name: Execute force logrotate
      ansible.builtin.command:
        cmd: logrotate /etc/logrotate.d/nginx -f -v
      changed_when: false
      register: result
    - name: Assert exet code
      ansible.builtin.assert:
        that:
          - result.rc == 0
    - name: Check logrotate entry(MariaDB)
      ansible.builtin.stat:
        path: /etc/logrotate.d/mariadb
      register: result
    - name: Assert file(MariaDB logrotate setting)
      ansible.builtin.assert:
        that:
          - result.stat.exists
    - name: Execute force logrotate
      ansible.builtin.command:
        cmd: logrotate /etc/logrotate.d/mariadb -f -v
      changed_when: false
      register: result
    - name: Assert exet code
      ansible.builtin.assert:
        that:
          - result.rc == 0
    - name: Check logrotate entry(Apache)
      ansible.builtin.stat:
        path: /etc/logrotate.d/apache2
      register: result
    - name: Assert file(Apache logrotate setting)
      ansible.builtin.assert:
        that:
          - result.stat.exists
    - name: Execute force logrotate
      ansible.builtin.command:
        cmd: logrotate /etc/logrotate.d/apache2 -f -v
      changed_when: false
      register: result
    - name: Assert exet code
      ansible.builtin.assert:
        that:
          - result.rc == 0
